### ISSUE TITLE
ask about nkinopoiskpy

### ISSUE THREAD

**Issue by unicodick** [lunakoly/ArrrghForKotlin#1]
Hi, if you are the developer of this library, is it possible to access it?

I found the git clone repository https://github.com/lunakoly/nkinopoiskpy Sorry if it's not you

**Comment by lunakoly** [comment]
Hi, @setunicode! Sorry for the late response, I missed the notification. I'm afraid I'm not familiar with what https://github.com/lunakoly/nkinopoiskpy is, could you please give me a bit more context?

**Comment by unicodick** [comment]
Hi again, it was my mistake, I confused the author, I apologize again

this is a library for python
